name: Check for new Jellyfin release

on:
  workflow_dispatch: # Allow for manually triggering the workflow
  schedule:
    - cron: "0 15 * * *" # Everyday at 3PM UTC (5PM Europe/Paris)

env:
  WATCHING_REPO: GeoffreyCoulaud/jellyfin-api-client
  WATCHED_REPO: jellyfin/jellyfin

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release tag
        id: watching_repo
        run: |
          tag=$(curl --silent "https://api.github.com/repos/$WATCHING_REPO/releases/latest" | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Get latest Jellyfin release tag
        id: watched_repo
        run: |
          tag=$(curl --silent "https://api.github.com/repos/$WATCHED_REPO/releases/latest" | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Compare versions and update issue if necessary
        id: create_issue
        run: |
          WATCHING_REPO_TAG="${{ steps.watching_repo.outputs.tag }}"
          echo "$WATCHING_REPO latest tag: $WATCHING_REPO_TAG"
          WATCHED_REPO_TAG="${{ steps.watched_repo.outputs.tag }}"
          echo "$WATCHED_REPO latest tag: $WATCHED_REPO_TAG"

          ISSUE_NUMBER=$(curl --silent "https://api.github.com/repos/$WATCHING_REPO/issues?state=all" | jq '.[] | select(.title == "Update to new release of Jellyfin") | .number')
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "Creating new issue."
            curl \
              --silent \
              -X POST \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$WATCHING_REPO/issues" \
              -d '{"title":"Update to new release of Jellyfin","body":"A new release of Jellyfin is available: '$WATCHED_REPO_TAG'"}'
          fi

          MOST_RECENT=$(printf '%s\n' "$WATCHING_REPO_TAG" "$WATCHED_REPO_TAG" | sort -V | head -n1)
          if [ "$MOST_RECENT" != "$WATCHING_REPO_TAG" ]; then
            echo "A new release of Jellyfin is available: $WATCHED_REPO_TAG."
            echo "Reopening issue #$ISSUE_NUMBER."
            curl \
              --silent \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$WATCHING_REPO/issues/$ISSUE_NUMBER" \
              -d '{"state":"open","state_reason":"reopened"}'
          else
            echo "No new release of Jellyfin found."
            echo "Closing issue #$ISSUE_NUMBER."
            curl \
              --silent \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$WATCHING_REPO/issues/$ISSUE_NUMBER" \
              -d '{"state":"closed","state_reason":"completed"}'
          fi
